baseURL = "/"
languageCode = "en-us"
title = "Seyoung Kim"
theme = "archie"
copyright = "© Seyoung Kim"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

[params]
mode = "auto"
subtitle = "Welcome!"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/seyoungjkim"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/seyoungjkim"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
