baseURL = "https://seyoungjkim.github.io/"
languageCode = "en-us"
title = "Seyoung Kim"
theme = "archie"
copyright = "© Seyoung Kim"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "auto"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/seyoungjkim"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/seyoungjkim"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/seyoungjkim"
